### ISSUE TITLE
torch.OutOfMemoryError: Allocation on device

### ISSUE THREAD

**Issue by xueqing0622** [instantX-research/InstantIR#7]
3060 12G 显存不够，
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 12.68it/s]
use lora alpha 1
use lora alpha 1
use lora alpha 8.0
Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
use lcm lora alpha 8.0
Loading checkpoint...
loading checkpoint done.
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantIR_Wrapper\InstantIR_node.py", line 105, in main_
    model.to(device=device, dtype=torch_dtype)
  File "F:\ComfyUI\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 431, in to
    module.to(device, dtype)
  File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 8 more times]
  File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1160, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.

**Comment by WalkingwithAI** [comment]
同样也是爆显存，请问作者，有精简一些的模型吗？

**Comment by WalkingwithAI** [comment]
> Hi all, though InstantIR's pipeline does not rely on any special design of SDXL, which means it is possible to have a sd-2.1/1.5 version of InstantIR. But unfortunately we do not have these smaller version on schedule right now. It is recommended to run InstantIR on machines with VRAM more than 22GB. The good thing is our space demo is online, powered by ZeroGPU. You can directly play with InstantIR on https://huggingface.co/spaces/JOY-Huang/InstantIR

OK, Thank you so much.
